### ISSUE TITLE
Prepare the agenda for the 5th. International Project Coordination Meeting

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/WP5#91]
https://docs.google.com/document/d/1Sxia29BVlSAeLshtSm14iJi2z6762YD-tNFllPq9og8/edit

**Comment by mrostren** [comment]
Hello Ferhat, @ferhaterata 

I have edit the agenda by adding Yvan name to the invited guests list...
And I have added also the last topic (Yvan joins the project ...)
Regards

**Comment by ferhaterata** [comment]
Thanks.
